const OK_CODE = 200;
const CREATE_CODE = 201;
const INPUT_ERROR_CODE = 400;
const NOTFOUND_ERROR_CODE = 404;
const ERROR_CODE = 500;
const SALT_ROUND = 10;

module.exports = {
  OK_CODE,
  CREATE_CODE,
  INPUT_ERROR_CODE,
  NOTFOUND_ERROR_CODE,
  ERROR_CODE,
  SALT_ROUND,
};
